[package]
name = "nftables-async"
version = "0.1.0"
edition = "2021"

[dependencies]
nftables = "0.5.0"
serde_json = "1.0.132"
tokio = { version = "1.41.0", default-features = false, features = [
    "process",
    "io-util",
] }
